language: python
python:
  - "3.7"
  - "3.8"
install:
 # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install codecov
  - pip install tox-travis tox-conda
script:
  - tox
after_success:
  - codecov # submit coverage
